import type { Post } from "./types";

// バックエンド未接続のためのモックデータ
export const MOCK_POSTS: Post[] = [
  {
    id: "1",
    category: "match",
    teamName: "世田谷ベースボールクラブ",
    eventDate: "2026-07-12T09:00:00+09:00",
    prefecture: "東京都",
    venue: "駒沢オリンピック公園 軟式野球場",
    level: "highschool",
    fee: 3000,
    capacity: null,
    ageGroup: "30代中心",
    highCorBat: "ng",
    meetingTime: "08:30",
    meetingPlace: "駒沢オリンピック公園 第一球場 バックネット裏",
    description:
      "30〜40代中心のエンジョイチームです。日曜午前に練習試合をしていただけるチームを募集しています。軟式（M号）、7イニング制、審判は双方で出し合いをお願いします。球場代は折半で1チームあたり3,000円程度です。和やかに楽しくやりましょう！",
    status: "open",
    createdAt: "2026-06-20T10:00:00+09:00",
    contact: "setagaya-bbc@example.com",
    teamUrl: "https://example.com/teams/setagaya-bbc",
  },
  {
    id: "2",
    category: "helper",
    teamName: "横浜グリーンズ",
    eventDate: "2026-07-05T13:00:00+09:00",
    prefecture: "神奈川県",
    venue: "新横浜公園 第3軟式野球場",
    level: "college",
    fee: null,
    capacity: 1,
    positions: ["OF"],
    ageGroup: "30代中心",
    highCorBat: "ng",
    meetingTime: "12:30",
    meetingPlace: "新横浜公園 第3球場 バックネット裏",
    description:
      "リーグ戦で人数が足りず、外野を守れる助っ人を1名募集します。経験者だと助かりますが、しっかり守備ができれば大歓迎。参加費は無料です。道具は基本ご持参ください（グローブのみでOK、バット・ヘルメットは貸出あり）。",
    status: "closing_soon",
    createdAt: "2026-06-25T18:30:00+09:00",
    contact: "090-0000-0000",
  },
  {
    id: "3",
    category: "ground",
    teamName: "多摩川ファイターズ",
    eventDate: "2026-07-18T13:00:00+09:00",
    prefecture: "東京都",
    venue: "多摩川河川敷 野球場（大田区側）",
    level: "any",
    fee: 2000,
    capacity: null,
    description:
      "予定していた試合が中止になったため、押さえている土曜午後（13:00〜16:00）の枠をお譲りします。利用料は実費の2,000円のみ。河川敷ですがネット完備、駐車スペースあり。先着順とさせていただきます。",
    status: "open",
    createdAt: "2026-06-26T08:00:00+09:00",
    contact: "tamagawa.fighters@example.com",
  },
  {
    id: "4",
    category: "match",
    teamName: "さいたまサンデーズ",
    eventDate: "2026-08-02T10:00:00+09:00",
    prefecture: "埼玉県",
    venue: "大宮第二公園 軟式野球場",
    level: "juniorhigh",
    fee: 2500,
    capacity: null,
    description:
      "野球を始めたばかりのメンバーが多いチームです。勝ち負けよりも楽しむことを大切にしています。同じくらいのレベルのチームと練習試合できたら嬉しいです。女性メンバーも在籍しています。お気軽にご連絡ください。",
    status: "open",
    createdAt: "2026-06-22T12:00:00+09:00",
  },
  {
    id: "5",
    category: "helper",
    teamName: "大阪イーグルス",
    eventDate: "2026-07-11T14:00:00+09:00",
    prefecture: "大阪府",
    venue: "舞洲ベースボールスタジアム 第2",
    level: "college",
    fee: null,
    capacity: 2,
    positions: ["P"],
    ageGroup: "20代中心",
    highCorBat: "ok",
    meetingTime: "13:30",
    meetingPlace: "舞洲ベースボールスタジアム 第2 正面ゲート",
    description:
      "ある程度投げられるピッチャーを1〜2名募集します。試合形式の練習で、しっかり野球をやりたい方向けです。経験者・現役世代歓迎。参加費は無料です。試合後に近くで軽く打ち上げ予定です（任意参加）。",
    status: "open",
    createdAt: "2026-06-24T21:00:00+09:00",
    contact: "osaka.eagles@example.com",
    teamUrl: "https://example.com/teams/osaka-eagles",
  },
  {
    id: "6",
    category: "match",
    teamName: "名古屋ナイトホークス",
    eventDate: "2026-07-16T19:00:00+09:00",
    prefecture: "愛知県",
    venue: "名古屋市港北公園 野球場",
    level: "college",
    fee: 4000,
    capacity: null,
    ageGroup: "20代中心",
    highCorBat: "ok",
    meetingTime: "18:45",
    meetingPlace: "港北公園 野球場 入口",
    description:
      "平日夜にナイターで練習試合できるチームを募集します。20〜30代中心、そこそこ本気でやっています。照明代込みで1チーム4,000円程度。19:00開始、21:00までの時間貸しです。",
    status: "open",
    createdAt: "2026-06-19T23:00:00+09:00",
  },
  {
    id: "7",
    category: "ground",
    teamName: "博多リバーサイド",
    eventDate: "2026-07-26T08:00:00+09:00",
    prefecture: "福岡県",
    venue: "東平尾公園 博多の森軟式野球場",
    level: "any",
    fee: null,
    capacity: null,
    description:
      "毎週押さえている枠が今回空いたため譲ります。利用料は当方が支払い済みのため無料ですが、簡単な整備のご協力をお願いします。朝8:00〜11:00。気持ちよく使っていただける方へ。",
    status: "open",
    createdAt: "2026-06-21T07:30:00+09:00",
    contact: "hakata.riverside@example.com",
  },
  {
    id: "8",
    category: "helper",
    teamName: "札幌ノーススターズ",
    eventDate: "2026-06-28T10:00:00+09:00",
    prefecture: "北海道",
    venue: "円山球場 補助グラウンド",
    level: "college",
    fee: null,
    capacity: 1,
    description:
      "キャッチャーができる方を募集していましたが、無事に決まりました。たくさんのご連絡ありがとうございました。また機会がありましたらよろしくお願いします。",
    status: "closed",
    createdAt: "2026-06-15T11:00:00+09:00",
  },
  {
    id: "9",
    category: "match",
    teamName: "神戸ベイスターズ",
    eventDate: "2026-08-09T13:00:00+09:00",
    prefecture: "兵庫県",
    venue: "神戸総合運動公園 軟式野球場",
    level: "highschool",
    fee: 3500,
    capacity: null,
    description:
      "結成3年目のエンジョイチームです。月1〜2回ペースで活動しています。お互い楽しく試合ができればと思っています。球場代は折半でお願いします。よろしくお願いします！",
    status: "open",
    createdAt: "2026-06-27T09:00:00+09:00",
  },
  {
    id: "10",
    category: "helper",
    teamName: "仙台ブレイブス",
    eventDate: "2026-07-19T09:00:00+09:00",
    prefecture: "宮城県",
    venue: "シェルコムせんだい",
    level: "highschool",
    fee: null,
    capacity: 2,
    positions: ["1B", "2B", "3B", "SS"],
    ageGroup: "幅広い年代",
    meetingTime: "08:30",
    meetingPlace: "シェルコムせんだい 正面入口",
    description:
      "地域の大会に出場するため、内野を守れる助っ人を2名募集します。レベルはエンジョイ寄りなので気軽にご参加ください。参加費は無料です。試合は1日2〜3試合の予定です。",
    status: "closing_soon",
    createdAt: "2026-06-26T19:00:00+09:00",
    contact: "sendai.braves@example.com",
  },
  {
    id: "11",
    category: "ground",
    teamName: "広島カープシティ",
    eventDate: "2026-07-23T16:00:00+09:00",
    prefecture: "広島県",
    venue: "広島市民球場跡地 多目的グラウンド",
    level: "any",
    fee: 1500,
    capacity: null,
    description:
      "平日夕方16:00〜18:00の枠を譲ります。練習にちょうど良い広さです。利用料1,500円。お早めにご連絡ください。",
    status: "open",
    createdAt: "2026-06-23T14:00:00+09:00",
  },
  {
    id: "12",
    category: "match",
    teamName: "千葉サンダーボルツ",
    eventDate: "2026-08-16T10:00:00+09:00",
    prefecture: "千葉県",
    venue: "千葉県野球場",
    level: "college",
    fee: 5000,
    capacity: null,
    description:
      "本気で野球に取り組んでいるチームです。同じく真剣に取り組むチームと試合がしたいです。9イニング、公式ルール準拠。球場代は折半（1チーム5,000円程度）。レベルの高い試合をしましょう。",
    status: "open",
    createdAt: "2026-06-18T20:00:00+09:00",
    contact: "chiba.thunder@example.com",
  },
];

export function getPostById(id: string): Post | undefined {
  return MOCK_POSTS.find((p) => p.id === id);
}
